/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2012 (11.0.5058)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2012
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [DB5693_SAIDA]
GO

/****** Object:  StoredProcedure [Arquivo].[SAISP014_CSV_252]    Script Date: 14/09/2017 13:05:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [Arquivo].[SAISP014_CSV_252]  AS BEGIN


SET DATEFORMAT YMD

DECLARE @dt_inicio as smalldatetime
SET @dt_inicio= (SELECT DT_MOVIMENTO_ATUAL FROM [DB5693_CONTROLE].[Arquivo].[CONTB001_PROCESSO] WHERE NU_PROCESSO=26)

SELECT
	  [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_CONTRATO as idContrato
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_CPF_CNPJ_MUTUARIO as CPFCGCMutuario
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_LOGRADOURO_IMOVEL as  tipoLogradouroImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_TIPO_LOGRADOURO_IMOVEL as tipoLogradouroImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_NUMERO_IMOVEL as nomeLogradouroImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_COMPLEMENTO_IMOVEL as complementoImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_BAIRRO_IMOVEL as bairroImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_CIDADE_IMOVEL as cidadeImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_UF_IMOVEL as UFImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].ED_CEP_IMOVEL as CEPImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].VR_SALDO_DEVEDOR_INICIAL AS vlrSaldoDevedorInicial
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].VR_COMPRA_VENDA_IMOVEL AS vlrCompraVendaImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].VR_AVALIACAO_IMOVEL AS vlrAvaliacaoImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].PC_TAXA_JUROS_INICIAL AS percTaxaJurosInicial
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].PC_TAXA_JUROS_ATUAL AS percTaxaJurosAtual
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_CER AS idUnidadeOperacional
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_UNIDADE_OPERACIONAL AS idUnidadeOperacional
	, [DB5693_SIACI].[PARAMETRO].[ACITBC02_CATEGORIA_IMOVEL].NU_CATEGORIA_IMOVEL AS  idCategoriaImovel
	, [DB5693_SIACI].[PARAMETRO].[ACITBC02_CATEGORIA_IMOVEL].NO_CATEGORIA_IMOVEL AS dscCategoriaImovel
	, [DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA].NU_TIPO_IMOVEL AS idTipoImovel
	, [DB5693_SIACI].[PARAMETRO].[ACITBT13_TIPO_IMOVEL].NO_TIPO_IMOVEL AS dscTipoImovel
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_ORIGEM_RECURSO AS idOrigemRecursos
	, [DB5693_SIACI].[PARAMETRO].[ACITBO02_ORIGEM_RECURSO].NO_ORIGEM_RECURSO AS dscOrigemRecursos
	, [DB5693_SIACI].[PARAMETRO].[ACITBL02_LINHA_FINANCIAMENTO].NU_LINHA_FINANCIAMENTO AS idLinhaFinanciamento
	, [DB5693_SIACI].[PARAMETRO].[ACITBL02_LINHA_FINANCIAMENTO].NO_LINHA_FINANCIAMENTO AS dscLinhaFinanciamento
	, [DB5693_SIACI].[PARAMETRO].[ACITBT11_TIPO_FINANCIAMENTO].NU_TIPO_FINANCIAMENTO AS idTipoFinanciamento
	, [DB5693_SIACI].[PARAMETRO].[ACITBT11_TIPO_FINANCIAMENTO].NO_TIPO_FINANCIAMENTO AS dscTipoFinanciamento
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].DT_ASSINATURA_CONTRATO AS dtContratacao
	, YEAR([DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].DT_ASSINATURA_CONTRATO)  as  Safra
	, MONTH([DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].DT_ASSINATURA_CONTRATO) as Mes
	, [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].VR_RENDA_FAMILIAR_COMPROVADA AS vlrRendaFamiliarComprovada
	, [DB5693_SIACI].[PARAMETRO].[ACITBM03_MUNICIPIO].NO_MUNICIPIO AS Municipio
	, [DB5693_SIACI].[PARAMETRO].[ACITBM03_MUNICIPIO].NU_MUNICIPIO AS CodigoMunicipio

	FROM    [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ] 

	INNER JOIN [DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA] 
		ON [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_REGENCIA_CRITICA = [DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA].NU_REGENCIA_CRITICA 
		AND 
			[DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA].NU_CREDOR=1102
	
	INNER JOIN [DB5693_SIACI].[PARAMETRO].[ACITBL02_LINHA_FINANCIAMENTO] 
		ON [DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA].NU_LINHA_FINANCIAMENTO = [DB5693_SIACI].[PARAMETRO].[ACITBL02_LINHA_FINANCIAMENTO].NU_LINHA_FINANCIAMENTO 

	INNER JOIN [DB5693_SIACI].[PARAMETRO].[ACITBT11_TIPO_FINANCIAMENTO] 
		ON [DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA].NU_TIPO_FINANCIAMENTO = [DB5693_SIACI].[PARAMETRO].[ACITBT11_TIPO_FINANCIAMENTO].NU_TIPO_FINANCIAMENTO 

	INNER JOIN [DB5693_SIACI].[PARAMETRO].[ACITBC02_CATEGORIA_IMOVEL] 
		ON [DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA].NU_CATEGORIA_IMOVEL = [DB5693_SIACI].[PARAMETRO].[ACITBC02_CATEGORIA_IMOVEL].NU_CATEGORIA_IMOVEL 
	
	INNER JOIN [DB5693_SIACI].[PARAMETRO].[ACITBT13_TIPO_IMOVEL] 
		ON [DB5693_SIACI].[PARAMETRO].[ACITBR01_REGENCIA_CRITICA].NU_TIPO_IMOVEL = [DB5693_SIACI].[PARAMETRO].[ACITBT13_TIPO_IMOVEL].NU_TIPO_IMOVEL

	INNER JOIN [DB5693_SIACI].[PARAMETRO].[ACITBO02_ORIGEM_RECURSO] 
		ON 	[DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_ORIGEM_RECURSO = [DB5693_SIACI].[PARAMETRO].[ACITBO02_ORIGEM_RECURSO].NU_ORIGEM_RECURSO


	INNER JOIN [DB5693_SIACI].[MOVIMENTO].[ACITB001_PEDIDO_ATIVO]
		ON 
			[DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_CONTRATO = [DB5693_SIACI].[MOVIMENTO].[ACITB001_PEDIDO_ATIVO].NU_CONTRATO 
			AND
			[DB5693_SIACI].[MOVIMENTO].[ACITB001_PEDIDO_ATIVO].NU_ESTADO_PEDIDO = 1
			AND 
			[DB5693_SIACI].[MOVIMENTO].[ACITB001_PEDIDO_ATIVO].NU_TIPO_PEDIDO = 1
	
	LEFT JOIN [DB5693_SIACI].[PARAMETRO].[ACITBM03_MUNICIPIO] 
		ON 
			[DB5693_SIACI].[MOVIMENTO].[ACITB001_PEDIDO_ATIVO].NU_MUNICIPIO_IMOVEL =[DB5693_SIACI].[PARAMETRO].[ACITBM03_MUNICIPIO].NU_MUNICIPIO
		AND
			[DB5693_SIACI].[MOVIMENTO].[ACITB001_PEDIDO_ATIVO].NU_ESTADO_PEDIDO = 1
		AND 
	[DB5693_SIACI].[MOVIMENTO].[ACITB001_PEDIDO_ATIVO].NU_TIPO_PEDIDO = 1
	
	WHERE 
	([DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].DT_ASSINATURA_CONTRATO) >= (SELECT DATEADD(mm,-1,(DATEADD(mm, DATEDIFF(mm,0,@Dt_inicio), 0))))
	AND [DB5693_SIACI].[SILIQ].[ACITB001_SILIQ].NU_TIPO_PESSOA = 1




END
GO

